### ISSUE TITLE
Install UniVRM with UPM

### ISSUE THREAD

**Issue by cactusgamer1** [vrm-c/vrm.dev#231]
why is it so hard for you to just give a download link instead of a bunch of links that do nothing? like I've been searching for the download link and I've now clicked on EVERY SINGLE ONE OF THE LINKS and NONE have been the download link

**Comment by PoChang007** [comment]
hmm...maybe we should mention where to download UniVRM package on top of the release page, just make sure no one get lost. In the release page, click the `UniVRM-0.XX.X_XXXX.unitypackage`:

![download_univrm](https://user-images.githubusercontent.com/17579532/127745599-b07eb114-666f-4e74-97ad-965453f04f8d.jpg)

Then import the downloaded Unity package into your Unity project:
https://vrm.dev/en/docs/univrm/install/univrm_install/#import-unitypackage

**Comment by PoChang007** [comment]
We have added more information in the release page.  
https://github.com/vrm-c/UniVRM/releases

thanks,
