### ISSUE TITLE
VRMフォーマット技術仕様 / VRM仕様  「定義しているボーン」で shoulder が欠けている

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/vrm.dev#24]
https://vrm.dev/vrm_spec/#%E5%AE%9A%E7%BE%A9%E3%81%97%E3%81%A6%E3%81%84%E3%82%8B%E3%83%9C%E3%83%BC%E3%83%B3

**Comment by ykzts** [comment]
Did this issue resolve in #29?

**Comment by esperecyan** [comment]
Yes, thank you!
