### ISSUE TITLE
要望：VRMドキュメントをSphinxで作成するのを止めたい

### ISSUE THREAD

**Issue by FujiSunflower** [vrm-c/vrm.dev#276]
VRMドキュメントに使われているSphinxはプログラミングを分かる人が楽をするためものですので、ウェブデザイナーの方が関与しづらくなっています。
人間が読めない言葉で書かれたドキュメントになっていて、アプリ開発者がわざわざVRMの資料を集める必要があり規格の利用が伸びていません。
コミット履歴を見るとousttrueさんがプルリクを確認してコミットする手順になっているので結局一人で管理しているようなものです。
VRMコンソーシアムで専任のウェブデザイナーの方に依頼して使いやすい方法でウェブページを作って頂いた方が良いと思います。

**Comment by ousttrue** [comment]
他に人居ないんだよね

**Comment by ousttrue** [comment]
不毛だ
