### ISSUE TITLE
[1.0] ドキュメント案

### ISSUE THREAD

**Issue by ousttrue** [vrm-c/vrm.dev#285]
ドキュメントの構成案です。

|分類|-|
|-|-|
|共|0.x と 1.0 で共用にできる。既存ページを流用して章立てを新しくする|
|旧|0.x 用。旧バージョン用のフォルダに下げる|
|新|1.0用。新しい章立てで作る|

- [ ] `共` VRMとは https://vrm.dev/vrm/vrm_about.html#id1
    - [ ] `共` 理念、できること・できないこと https://vrm.dev/vrm/vrm_about.html#id1
- [ ] `新` VRMアバターを作る https://vrm.dev/vrm/how_to_make_vrm/index.html
    - [ ] `新` UniVRMを使ったアバターモデルのセットアップ
        - [ ] `新` Step by Stepガイド
    - [ ] `新` VRMアバターを動かしてみる
        - [ ] `新` サンプルビューア
        - [ ] `新` Web/使用できるアプリケーション
    - [ ] `新` VRMに設定できるライセンスは？
        - [ ] `新` パブリック・ライセンス文書
    - [ ] `新` VRMセットアップリファレンス
        - [ ] `新` 表情をつけてみる（Expression）
            - [ ] `新` 一般的な設定手順(Morph/Blendshape)
            - [ ] `新` 一般的な設定手順(Material Switch)
            - [ ] `新` 一般的な設定手順(UV offset)
            - [ ] `新` リファレンス
        - [ ] `新` 視線を制御してみる（LookAt）
            - [ ] `新` 一般的な設定手順(Eye bone/UV offset)
            - [ ] `新` 確認方法
            - [ ] `新` リファレンス
        - [ ] `新` 質感を設定してみる（Material）
            - [ ] `新` 一般的な設定手順
            - [ ] `新` リファレンス
        - [ ] `新` 揺れものを制御してみる（SpringBone）
            - [ ] `新` 一般的な設定手順
            - [ ] `新` よく使われる設定パターン
            - [ ] `新` リファレンス
        - [ ] `新` コンストレイントを設定してみる（Constraint）
            - [ ] `新` 一般的な設定手順
            - [ ] `新` よく使われる設定パターン
            - [ ] `新` リファレンス
        - [ ] `新` 一人称視点を定義してみる（FirstPerson）
            - [ ] `新` 一般的な設定手順
            - [ ] `新` リファレンス
        - [ ] `新` 基本姿勢を把握しておく（TPose/Humanoid）
            - [ ] `新` リファレンス
    - [ ] `共` VRMセットアップ・トラブルシューティング
        - [ ] `共` エラーとその原因
        - [ ] `共` FAQ
    - [ ] `新?` DCCツールでのVRMセットアップ（軽い紹介）
        - [ ] `新?` Blender
- [ ] `新` VRMアバターを使うアプリケーションを作る https://vrm.dev/vrm/vrm_development.html
    - [ ] `新` VRMファイルを読み込むためのライブラリ紹介
        - [ ] `新` UniVRM
        - [ ] `新?` ThreeVRM
        - [ ] `新?` VRM4U
        - [ ] `新?` Godot Engine?
    - [ ] `新` UniVRMを使ってVRMアバターを表示する
        - [ ] `新` Step by Stepガイド
        - [ ] `新` こういうときにはどうすれば？(サンプルコードつき解説)
            - [ ] `新` アバターにアニメーションを当てたい
            - [ ] `新` アバターの表情を操作したい
            - [ ] `新` アバターの口パクを動かしたい
            - [ ] `新` アバターの目線を制御したい
    - [ ] `新` UniVRMトラブルシューティング
        - [ ] `新` エラーとその原因
        - [ ] F`新` AQ
    - [ ] UniVRMリファレンス https://vrm-c.github.io/UniVRM/ja/
        - [ ] APIリファレンス https://vrm-c.github.io/UniVRM/ja/

# 現状

![current](https://user-images.githubusercontent.com/68057/177754689-66a09605-f66d-4753-a375-94dbb17a97f1.jpg)

開発者向けは

https://vrm-c.github.io/UniVRM/ja/

に分離してます。

**Comment by mendosu** [comment]
各項目に含まれる属性や要素の簡単な説明だけでもまずは欲しいです。0．x系だとドキュメント等に説明が無いためどういう挙動に影響があるのかすら判断できない謎のパラメータも在りました（SpringBoneのCenterのこと）、要素の名称だけで一体何を意味してるのか理解するのは非常に困難です。

SpringBoneで言うと

**Stiffness Force**→剛性、元に戻る強さ
**Gravity Powe**r→ 重力の強さ
**Gravity Dir**→ 重力の向き
**Drag Force**→抵抗力、強いと動きが鈍くなる
**Center**→揺れの基準、指定しない場合ワールド原点が基準になる。

使用例や設定手順の前にこういった**一つ一つの項目について簡単な説明**を全て出して欲しいです。

　ここで例にあげている「Center」は大抵のVRM製作者さんは「中心？スプリングボーンの？スカートなら腰(hip)かな？」「あれ？揺れなくなった！触らないでおこう」となります。

**Comment by ousttrue** [comment]
とりえあずこの issue は使われなかったので close します

**Comment by mendosu** [comment]
使われてないのはこのissueではなくVRM1.0そのものです。
タイミング的にもVRM1.0についてユーザーが増えるのは来年以降です、
このissueに興味を持ったり書き込みをしたくなる人間が出てくるだろうタイミングは、丁度今頃から来年2024年にかけての時期になるかと思います。
ここはこれから必要になると思います。
