### ISSUE TITLE
Human bone spec was changed silently.

### ISSUE THREAD

**Issue by saturday06** [vrm-c/vrm.dev#31]
https://github.com/vrm-c/vrm.dev/pull/29/files こちらのマージ済みのプルリクエストですが、 以前まで `[^notrequired]` の記載が無かった `chest` と `neck` のボーンが `Optional` とマークされていて仕様変更が発生しています。そのため、spec versionを増やすか、この変更部分だけリバートをする必要があります。

**Comment by saturday06** [comment]
関連する議論はこちらで行われています→ https://github.com/vrm-c/vrm-specification/issues/10 

ただ、現状UnityのUIが `chest` と `neck` をOptionalとしていて現状の仕様はユーザーに優しくないので、取り急ぎspec versionを0.2へ更新し、そこで `chest` と `neck` をOptionalボーンとしてしまっても良いのかなと個人的に思っています。

以前必須ボーンについて ousttrue さんに伺った際の議論はこちら→ https://github.com/vrm-c/UniVRM/issues/113#issuecomment-451852579

**Comment by hiroj** [comment]
ご報告ありがとうございます。
実装(Unity)と一致させたほうが分かりやすいのは確かにそうですね。
いったんchestとneckは元の状態（必須）に戻し、議論の結果に合わせて変更することに致します。

**Comment by saturday06** [comment]
変更確認したためクローズします。ありがとうございました。
