### ISSUE TITLE
サイト整理

### ISSUE THREAD

**Issue by ousttrue** [vrm-c/vrm.dev#315]
## 英語版の管理方法を変更します。

gettext をやめて fork したレポジトリで管理します。

- [x] https://github.com/vrm-c/vrm.dev.en
- [x] テンプレートの言語スイッチの書き換え #316
- [x] 英語版の更新フローの整備 https://vrm.dev/release/how_to_translation
  vrm.dev.en で vrm.dev を pull する。ゆくゆくは部分的に自動化

## ドキュメントツールを [Docusaurus](https://docusaurus.io/docs) に更新します。

- [x] sphnx 👉 docusaurusへのリプレース。action 更新。orphan branch 使わない方式
- [x] sidebar のトップレベルをヘッダーに移動して一段階浅くする
- [x] UniVRM の開発記事と Release ノートをこっちに引越しする
- [x] 英語版の初期追随作業 https://github.com/vrm-c/vrm.dev.en/pull/7

## 別件 
- VRM-Animation の記事追加

**Comment by FujiSunflower** [comment]
> sidebar のトップレベルをヘッダーに移動して一段階浅くする。

ドキュメント周りたびたび言ってましたが良い傾向に思えます。
作業がうまく進むことを祈ります。

**Comment by ousttrue** [comment]
翻訳 workflow のメモ。
英語版の更新には２種類ある。

- 日本語版への追随
- 翻訳作業

前者は機械的な単純作業として手順化する。
github action 経由での自動化。
手動でやった時も追随作業のついでに翻訳することは避けるべし。

**Comment by ousttrue** [comment]
docusaurus への移行作業を完了します。
