### ISSUE TITLE
Unityのビルド設定の記事が抜けてしまっている気がする

### ISSUE THREAD

**Issue by FujiSunflower** [vrm-c/vrm.dev#370]
開発者向けページを移転した際にUnityのビルド設定の記事が抜けてしまっている気がします。
- Universal Render Pipeline のパッケージが必要になったこと
- StandardシェーダーをAlways Include Shadersに指定する必要があること

かつてのURL https://vrm-c.github.io/UniVRM/ja/build.html

**Comment by ousttrue** [comment]
復活しました。

https://vrm.dev/api/build/
