### ISSUE TITLE
What is the license for this repository?

### ISSUE THREAD

**Issue by ykzts** [vrm-c/vrm.dev#4]
The license for UniVRM is [MIT License](https://github.com/vrm-c/UniVRM/blob/v0.51.0/LICENSE.txt), but no `LICENSE` exists in this repository.

**Comment by ousttrue** [comment]
👍

**Comment by esperecyan** [comment]
@ousttrue こちらのissueはなぜクローズされているのでしょうか？

**Comment by esperecyan** [comment]
@ousttrue こちらのissueはなぜclosedになっているのでしょうか？
