### ISSUE TITLE
Broken link in 'How to view' page to 'showcase'

### ISSUE THREAD

**Issue by eburnette** [vrm-c/vrm.dev#413]
https://github.com/vrm-c/vrm.dev/blob/master/docs/vrm/how_to_view_vrm.md
has a broken link to
https://github.com/vrm-c/vrm.dev/blob/master/showcase
I get a 404 not found error.
I looked in the vrm1 directory but didn't see instructions on how to view.

I'm trying to find out if I can view and animate characters on a web page. Please point me in the right direction. Thank you very much.

**Comment by ousttrue** [comment]
The markdown in this repository has not yet been converted, so internal links will not be resolved.

Check out the built one here.

https://vrm.dev/vrm/how_to_view_vrm/
https://vrm.dev/en/vrm/how_to_view_vrm/
