### ISSUE TITLE
https://dwango.github.io/vrm/ からのリダイレクト

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/vrm.dev#45]
https://dwango.github.io/vrm/ で始まる旧URLのページからのリダイレクト先が、すべてトップページ https://vrm.dev/ になっているため、移行前に張られたリンクがリンク切れの状態になっています。旧URLについて、それぞれ対応するページへリダイレクトできませんか。

### 例
旧URL: https://dwango.github.io/vrm/how_to_make_vrm/
期待するリダイレクト先: https://vrm.dev/how_to_make_vrm/
実際のリダイレクト先: https://vrm.dev/

**Comment by ousttrue** [comment]
権限の都合で実施できず
