### ISSUE TITLE
VRMSpringBone - Cannot follow the docs

### ISSUE THREAD

**Issue by Scorbie** [vrm-c/vrm.dev#51]
Thank you for the thorough documentation; I could follow most of the steps except one, SpringBone settings. (https://vrm.dev/en/univrm/components/univrm_secondary/)
I could not follow the documentation because in the Hierarchy tab, there is no "secondary" node, and there wasn't a "VRM Spring Bone (Script)" to tinker on either.

UniVRM version: 0.55
Unity version: 2018.4.17f1 (64bit)
Platform: Windows 10

Thanks in advance.

**Comment by Scorbie** [comment]
Exporting the "combined" VRM and importing again did the trick, is it in line with the documentation's intention?

**Comment by PoChang007** [comment]
Thanks for pointing out. Yes, from step 4-6 in https://vrm.dev/en/how_to_make_vrm/, the original file needs to be exported as VRM and imported again, then the secondary node can be created. Maybe we should mention this in SpringBone section?

if you've imported UniVRM package, typing in "VRM Spring Bone" in search bar should work.

![search VRM Spring Bone](https://user-images.githubusercontent.com/17579532/75601174-ff048980-5afb-11ea-90c7-c22ac96431c2.jpg)

**Comment by Scorbie** [comment]
Whoops, I guess I was in an edge case! (I was adding a springbone collider group to an existing VRM made from VRoid Studio to bypass some problem inside LIV); I personally think this issue itself would be helpful enough for anyone else with the same problem. Thank you!
