### ISSUE TITLE
「VRM」って何？どんなことができる？

### ISSUE THREAD

**Issue by HhotateA** [vrm-c/vrm.dev#57]
"A person who can perform with this avatar"の翻訳が"アバターに人格を与えることの許諾範囲"なのは、ロールプレイの強制を指すような誤解があり、"アバターを操作することの許諾範囲"などのほうが適切そう。

**Comment by PoChang007** [comment]
返事おそくなって大変申し訳ございません。
ご指摘ありがとうございます。
ライセンスの内容（日英対照）はVRMC法務委員会で検討します。
