### ISSUE TITLE
og:image does not exist

### ISSUE THREAD

**Issue by pocketberserker** [vrm-c/vrm.dev#8]
Currently, `og:image` is defined `{{ .Site.BaseURL }}images/logo.png`:

https://github.com/vrm-c/vrm.dev/blob/24bfd81fca1627fb1ab143824421ca944b6d073e/layouts/partials/head.html#L18

but `static/images/logo.png` does not exist:

https://github.com/vrm-c/vrm.dev/tree/24bfd81fca1627fb1ab143824421ca944b6d073e/static/images

**Comment by hiroj** [comment]
thx, I put the logo of vrm.
